name: Build GDMBasics with horusec

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop
jobs:
  SAST_HORUSEC:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec version
          horusec start -p="./" -e="true" --disable-docker 
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake and dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install libsfml-dev

      - name: Build GDMBasics
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
