name: Horusec Security and build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  SAST_HORUSEC_PRE_BUILD:
    name: horusec-security-pre-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Running Horusec Security pre build
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./"
          

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake and dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install libsfml-dev

      - name: Build GDMBasics
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
  SAST_HORUSEC_POST_BUILD:
    name: horusec-security-post-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Running Horusec Security post build
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./"   
