name: Horusec Security and build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release

jobs:

  Horusec_Security_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Running Horusec Security pre build
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./" --output-format="text" --json-output-file="./horusec-output.txt"
      
      - name: Check for medium vulnerabilities
        run: |
          medium_count=$(grep -c "Severity: MEDIUM" ./horusec-output.txt)
          echo "Found $medium_count medium severity vulnerabilities"
          if [ "$medium_count" -gt 3 ]; then
            echo "Too many medium vulnerabilities found! Failing the build."
            exit 1
          fi
  
      - name: Set up CMake and dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install libsfml-dev

      - name: Build GDMBasics
        run: |
          mkdir build
          cd build
          cmake ..
          make
